# Generated by Django 5.2.8 on 2025-11-15 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_viruslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viruslog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='viruslog',
            name='action',
            field=models.CharField(choices=[('UPLOAD_OK', 'Temiz dosya yüklendi'), ('UPLOAD_INFECTED', 'Virüslü dosya reddedildi'), ('DELETE', 'Dosya silindi'), ('DOWNLOAD', 'Dosya indirildi')], default='system', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viruslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viruslog',
            name='sha256',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viruslog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
